server:
  port: 8090
  servlet:
    context-path: /ns2
spring:
  application:
    name: nacos-server2
  cloud:
    nacos:
      config:
        group: DUCK_GROUP
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        group: MY_GROUP
        server-addr: 127.0.0.1:8848
