server:
  port: 8088
spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        group: MY_GROUP
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: server1
          uri: lb://nacos-server1
          predicates:
            - Path: /s1/**
        - id: server2
          uri: lb://nacos-server2
          predicates:
            - Path: /s2/**


